name: Java CI

on:
  push:
    branches:
      - main   # This pipeline will run whenever there is a push to the "main" branch
  pull_request:
    branches:
      - main   # This pipeline will also run for pull requests to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Check out the repository code

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'  # Use JDK version 23

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B clean install  # -B flag is for non-interactive Maven build

    - name: Run Tests
      run: mvn test  # This will run the tests as part of the build process

    - name: Upload test results (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-test-results
        path: target/surefire-reports/*.xml  # Adjust to the location of your test results if different
